{{- if and .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data: 
   {{- tpl ((.Files.Glob "files/*.yaml").AsConfig) . | nindent 2 }}
{{- end }}